### ISSUE TITLE
moleculer-blog image missing or not accessible

### ISSUE THREAD

**Issue by guumaster** [ice-services/moleculer-examples#1]
Hi, I'm trying to run the example on `blog/docker/blog-micro` but won't start with `start.sh` script. It throws this error:

```
ERROR: repository moleculer-blog not found: does not exist or no pull access
```
Any ideas?

**Comment by icebob** [comment]
I will check it.

**Comment by icebob** [comment]
Before `start.sh` you have to create image with `build.image.sh` in the `blog` folder.
