### ISSUE TITLE
White screen in conduit example

### ISSUE THREAD

**Issue by GHNewbiee** [ice-services/moleculer-examples#10]
Hi,

I am trying to run the conduit example, but I get a big white screen!
Is this example complete?

Tia

**Comment by icebob** [comment]
Yes, it's complete. Check the console logs in the browser.

**Comment by GHNewbiee** [comment]
I use Firefox 56.0.2 (64-bit). I can see only a white screen.

I have installed Midori, and I can run the site!

Thanks and I apologise for any inconvenience.
