### ISSUE TITLE
validateEntity() method is a built in method or not ???

### ISSUE THREAD

**Issue by a7me63azzab** [ice-services/moleculer-examples#11]
when i read code i found **this.validateEntity(entity)**  ok 
**this**  => refere to the service instance and we use it to access all methods in methods:{} .
but when i scroll down to find this method in methods:{} i found nothing , **where is this method ????**

**Comment by icebob** [comment]
It comes from `moleculer-db`: https://github.com/moleculerjs/moleculer-db/blob/8b7c46cafe71556c076fa54e03b230625a12f459/packages/moleculer-db/src/index.js#L705
