### ISSUE TITLE
Redis Cacher error

### ISSUE THREAD

**Issue by guumaster** [ice-services/moleculer-examples#2]
I'm trying the examples, it works fine with `Cachers.Memory` but it fails with `Cachers.Redis`. 

After debugging for a while, I found that the options were wrong and may need a fix:

```
    case 'redis':
      return new Cachers.Redis(process.env.MOL_REDIS_URI)
```
to this: 
```
    case 'redis':
      return new Cachers.Redis({ redis: process.env.MOL_REDIS_URI })
``` 

It can also be fixed by checking type on `RedisCacher` class' constructor: 

```
	constructor(opts) {
		opts = isString(opts) ? { redis: opts } : opts;
		super(opts);
	}
```

Then it got connected to redis properly.

**Comment by icebob** [comment]
Thanks. I will fix it. Just this example is made with a very earlier version of Moleculer. Next days I will update it.
